
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/p2p_uat?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.197.128
  profiles: # 指定激活读取哪个配置
    active: dev
  messages: # 指定去哪获取国际化语言包
    basename: i18n.login
  thymeleaf: # 开发时,可以选择禁用模板緩存
    cache: false
  mvc:
    date-format:  yyyy-MM-dd HH:mm:ss # 设置springmvc的时间格式

# 测试代码里获取配文件的内容
# 测试yml文件的各对象的写法;切记,value后面要有一个空格
person:
    lastName: zhangsan
    age: 18
    boss: false
    birth: 2018/09/22
    maps: {k1: 我是第一个值,"k2": "我是不转意/n的值",'k3': '我是转意/n的值'}
    alists:
      - 第一种list写法的第一个值
      - 第一种list写法的第二个值
    blists: [第二种list写法的第一个值,第二种list写法的第二个值]
    dog:
      name: 小狗對象的名稱
      age: 6
    email: 839817187@qq.com
    # 配置文件里可以用占位符${}来获取之前定义的值或者运行获取一些函数,获取失败还可以定义默认值用冒号
    testa: ${random.uuid:我是默认值}测试@$value单独获取
    testb: 测试@v#alue单独获取

# 修改端口
#server:
#  port: 8081
---
spring:
  profiles: dev # 当前文档块的名称
server:
  port: 8082
---
spring:
  profiles: prod
server:
  port: 8083
